from django.db import models

# Create your models here.
class importkey(models.Model):
    # id	= models.AutoField(primary_key=True)
    BOL	= models.TextField(null=True , blank=True)
    HOUSE_BILL	= models.TextField(null=True , blank=True)
    SUB_HOUSE_BILL	= models.TextField(null=True , blank=True)
    VOYAGE_NUMBER	= models.TextField(null=True , blank=True)
    BILL_TYPE	= models.TextField(null=True , blank=True)
    manifest	= models.TextField(null=True , blank=True)
    Trade_Update_Date	= models.TextField(null=True , blank=True)
    RUN_DATE	= models.TextField(null=True , blank=True)
    CARRIER_CODE	= models.TextField(null=True , blank=True)
    Vessel_Country_Code	= models.TextField(null=True , blank=True)
    Vessell_Name	= models.TextField(null=True , blank=True)
    Port_of_Unlading	= models.TextField(null=True , blank=True)
    Estimated_Arrival_Date	= models.TextField(null=True , blank=True)
    Foreign_Port_of_Lading_Qualifier	= models.TextField(null=True , blank=True)
    Foreign_Port_of_Lading	= models.TextField(null=True , blank=True)
    Manifest_Quanity	= models.TextField(null=True , blank=True)
    Manifest_Unit	= models.TextField(null=True , blank=True)
    Weight	= models.TextField(null=True , blank=True)
    Weight_Unit	= models.TextField(null=True , blank=True)
    Measurement	= models.TextField(null=True , blank=True)
    Measurement_Unit	= models.TextField(null=True , blank=True)
    Record_Status_Indicator	= models.TextField(null=True , blank=True)
    Place_of_Receipt	= models.TextField(null=True , blank=True)
    Port_of_Destination	= models.TextField(null=True , blank=True)
    Foreign_Port_of_Destination_Qualifier	= models.TextField(null=True , blank=True)
    Foreign_Port_of_Destination	= models.TextField(null=True , blank=True)
    Conveyance_ID_Qualifier	= models.TextField(null=True , blank=True)
    Conveyance_ID	= models.TextField(null=True , blank=True)
    IN_BOND_entry_type	= models.TextField(null=True , blank=True)
    Mode_of_Transportation	= models.TextField(null=True , blank=True)
    Actual_Arrival_Date	= models.TextField(null=True , blank=True)
    NOTIFY_PARTIES	= models.TextField(null=True , blank=True)
    shipper_name	= models.TextField(null=True , blank=True)
    Shipper_Address	= models.TextField(null=True , blank=True)
    country_code	= models.TextField(null=True , blank=True)
    Shipper_Contact_Info	= models.TextField(null=True , blank=True)
    Consignee_Name	= models.TextField(null=True , blank=True)
    Consignee_Address	= models.TextField(null=True , blank=True)
    # Country_Code	= models.TextField(null=True , blank=True)
    Consignee_Contact_Info	= models.TextField(null=True , blank=True)
    Notify_Party_Name	= models.TextField(null=True , blank=True)
    Notify_Address	= models.TextField(null=True , blank=True)
    Country_Code	= models.TextField(null=True , blank=True)
    Notify_Contact_Info	= models.TextField(null=True , blank=True)
    Container_Number	= models.TextField(null=True , blank=True)
    Container_Description_Sequence_Number	= models.TextField(null=True , blank=True)
    piece_count	= models.TextField(null=True , blank=True)
    Cargo_Description	= models.TextField(null=True , blank=True)
    Tariff_Informtion_from_record_61	= models.TextField(null=True , blank=True)
    Container_Info_from_Type_20_Record = models.TextField(null=True , blank=True)

    def __str__(self):
        return self.BOL

class importkey_new(models.Model):
    # id	= models.AutoField(primary_key=True)
    BOL	= models.TextField(null=True , blank=True)
    HOUSE_BILL	= models.TextField(null=True , blank=True)
    SUB_HOUSE_BILL	= models.TextField(null=True , blank=True)
    VOYAGE_NUMBER	= models.TextField(null=True , blank=True)
    BILL_TYPE	= models.TextField(null=True , blank=True)
    manifest	= models.TextField(null=True , blank=True)
    Trade_Update_Date	= models.TextField(null=True , blank=True)
    RUN_DATE	= models.TextField(null=True , blank=True)
    CARRIER_CODE	= models.TextField(null=True , blank=True)
    Vessel_Country_Code	= models.TextField(null=True , blank=True)
    Vessell_Name	= models.TextField(null=True , blank=True)
    Port_of_Unlading	= models.TextField(null=True , blank=True)
    Estimated_Arrival_Date	= models.TextField(null=True , blank=True)
    Foreign_Port_of_Lading_Qualifier	= models.TextField(null=True , blank=True)
    Foreign_Port_of_Lading	= models.TextField(null=True , blank=True)
    Manifest_Quanity	= models.TextField(null=True , blank=True)
    Manifest_Unit	= models.TextField(null=True , blank=True)
    Weight	= models.TextField(null=True , blank=True)
    Weight_Unit	= models.TextField(null=True , blank=True)
    Measurement	= models.TextField(null=True , blank=True)
    Measurement_Unit	= models.TextField(null=True , blank=True)
    Record_Status_Indicator	= models.TextField(null=True , blank=True)
    Place_of_Receipt	= models.TextField(null=True , blank=True)
    Port_of_Destination	= models.TextField(null=True , blank=True)
    Foreign_Port_of_Destination_Qualifier	= models.TextField(null=True , blank=True)
    Foreign_Port_of_Destination	= models.TextField(null=True , blank=True)
    Conveyance_ID_Qualifier	= models.TextField(null=True , blank=True)
    Conveyance_ID	= models.TextField(null=True , blank=True)
    IN_BOND_entry_type	= models.TextField(null=True , blank=True)
    Mode_of_Transportation	= models.TextField(null=True , blank=True)
    Actual_Arrival_Date	= models.TextField(null=True , blank=True)
    NOTIFY_PARTIES	= models.TextField(null=True , blank=True)
    shipper_name	= models.TextField(null=True , blank=True)
    Shipper_Address	= models.TextField(null=True , blank=True)
    country_code	= models.TextField(null=True , blank=True)
    Shipper_Contact_Info	= models.TextField(null=True , blank=True)
    Consignee_Name	= models.TextField(null=True , blank=True)
    Consignee_Address	= models.TextField(null=True , blank=True)
    Country_Code1	= models.TextField(null=True , blank=True)
    Consignee_Contact_Info	= models.TextField(null=True , blank=True)
    Notify_Party_Name	= models.TextField(null=True , blank=True)
    Notify_Address	= models.TextField(null=True , blank=True)
    Country_Code	= models.TextField(null=True , blank=True)
    Notify_Contact_Info	= models.TextField(null=True , blank=True)
    Container_Number	= models.TextField(null=True , blank=True)
    Container_Description_Sequence_Number	= models.TextField(null=True , blank=True)
    piece_count	= models.TextField(null=True , blank=True)
    Cargo_Description	= models.TextField(null=True , blank=True)
    Tariff_Informtion_from_record_61	= models.TextField(null=True , blank=True)
    Container_Info_from_Type_20_Record = models.TextField(null=True , blank=True)

    def __str__(self):
        return self.BOL



    #  BOL	 HOUSE_BILL	 SUB_HOUSE_BILL	 VOYAGE_NUMBER	 BILL_TYPE	 manifest	 Trade_Update_Date	 RUN_DATE	 CARRIER_CODE	 Vessel_Country_Code	 Vessell_Name	 Port_of_Unlading	 Estimated_Arrival_Date	 Foreign_Port_of_Lading_Qualifier	 Foreign_Port_of_Lading	 Manifest_Quanity	 Manifest_Unit	 Weight	 Weight_Unit	 Measurement	 Measurement_Unit	 Record_Status_Indicator	 Place_of_Receipt	 Port_of_Destination	 Foreign_Port_of_Destination_Qualifier	 Foreign_Port_of_Destination	 Conveyance_ID_Qualifier	 Conveyance_ID	 IN_BOND_entry_type	 Mode_of_Transportation	 Actual_Arrival_Date	 NOTIFY_PARTIES	 shipper_name	 Shipper_Address	 country_code	 Shipper_Contact_Info	 Consignee_Name	 Consignee_Address	 Country_Code	 Consignee_Contact_Info	 Notify_Party_Name	 Notify_Address	 Country_Code	 Notify_Contact_Info	 Container_Number	 Container_Description_Sequence_Number	 piece_count	 Cargo_Description	Tariff_Informtion_from_record_61	

    