# Generated by Django 4.0.3 on 2022-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='importkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOL', models.TextField(blank=True, null=True)),
                ('HOUSE_BILL', models.TextField(blank=True, null=True)),
                ('SUB_HOUSE_BILL', models.TextField(blank=True, null=True)),
                ('VOYAGE_NUMBER', models.TextField(blank=True, null=True)),
                ('BILL_TYPE', models.TextField(blank=True, null=True)),
                ('manifest', models.IntegerField(blank=True, null=True)),
                ('Trade_Update_Date', models.IntegerField(blank=True, null=True)),
                ('RUN_DATE', models.IntegerField(blank=True, null=True)),
                ('CARRIER_CODE', models.TextField(blank=True, null=True)),
                ('Vessel_Country_Code', models.TextField(blank=True, null=True)),
                ('Vessell_Name', models.TextField(blank=True, null=True)),
                ('Port_of_Unlading', models.TextField(blank=True, null=True)),
                ('Estimated_Arrival_Date', models.IntegerField(blank=True, null=True)),
                ('Foreign_Port_of_Lading_Qualifier', models.TextField(blank=True, null=True)),
                ('Foreign_Port_of_Lading', models.TextField(blank=True, null=True)),
                ('Manifest_Quanity', models.IntegerField(blank=True, null=True)),
                ('Manifest_Unit', models.TextField(blank=True, null=True)),
                ('Weight', models.IntegerField(blank=True, null=True)),
                ('Weight_Unit', models.TextField(blank=True, null=True)),
                ('Measurement', models.TextField(blank=True, null=True)),
                ('Measurement_Unit', models.TextField(blank=True, null=True)),
                ('Record_Status_Indicator', models.TextField(blank=True, null=True)),
                ('Place_of_Receipt', models.TextField(blank=True, null=True)),
                ('Port_of_Destination', models.TextField(blank=True, null=True)),
                ('Foreign_Port_of_Destination_Qualifier', models.TextField(blank=True, null=True)),
                ('Foreign_Port_of_Destination', models.TextField(blank=True, null=True)),
                ('Conveyance_ID_Qualifier', models.IntegerField(blank=True, null=True)),
                ('Conveyance_ID', models.TextField(blank=True, null=True)),
                ('IN_BOND_entry_type', models.TextField(blank=True, null=True)),
                ('Mode_of_Transportation', models.TextField(blank=True, null=True)),
                ('Actual_Arrival_Date', models.IntegerField(blank=True, null=True)),
                ('NOTIFY_PARTIES', models.TextField(blank=True, null=True)),
                ('shipper_name', models.TextField(blank=True, null=True)),
                ('Shipper_Address', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('Shipper_Contact_Info', models.TextField(blank=True, null=True)),
                ('Consignee_Name', models.TextField(blank=True, null=True)),
                ('Consignee_Address', models.TextField(blank=True, null=True)),
                ('Consignee_Contact_Info', models.TextField(blank=True, null=True)),
                ('Notify_Party_Name', models.TextField(blank=True, null=True)),
                ('Notify_Address', models.TextField(blank=True, null=True)),
                ('Country_Code', models.TextField(blank=True, null=True)),
                ('Notify_Contact_Info', models.TextField(blank=True, null=True)),
                ('Container_Number', models.TextField(blank=True, null=True)),
                ('Container_Description_Sequence_Number', models.IntegerField(blank=True, null=True)),
                ('piece_count', models.IntegerField(blank=True, null=True)),
                ('Cargo_Description', models.TextField(blank=True, null=True)),
                ('Tariff_Informtion_from_record_61', models.TextField(blank=True, null=True)),
                ('Container_Info_from_Type_20_Record', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
            ],
        ),
    ]
