# Generated by Django 4.0.3 on 2022-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_trial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importkey',
            name='Actual_Arrival_Date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importkey',
            name='Container_Description_Sequence_Number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importkey',
            name='Conveyance_ID_Qualifier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importkey',
            name='Estimated_Arrival_Date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importkey',
            name='Manifest_Quanity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importkey',
            name='RUN_DATE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importkey',
            name='Trade_Update_Date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importkey',
            name='Weight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importkey',
            name='manifest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importkey',
            name='piece_count',
            field=models.TextField(blank=True, null=True),
        ),
    ]
