# Generated by Django 4.0.3 on 2022-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_importkey_actual_arrival_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B', models.TextField()),
                ('C', models.TextField()),
                ('D', models.TextField()),
                ('E', models.TextField()),
                ('F', models.TextField()),
                ('G', models.TextField()),
                ('H', models.TextField()),
                ('I', models.TextField()),
                ('J', models.TextField()),
                ('K', models.TextField()),
                ('L', models.TextField()),
                ('M', models.TextField()),
                ('N', models.TextField()),
                ('O', models.TextField()),
                ('P', models.TextField()),
                ('Q', models.TextField()),
                ('R', models.TextField()),
                ('S', models.TextField()),
                ('T', models.TextField()),
                ('U', models.TextField()),
                ('V', models.TextField()),
                ('W', models.TextField()),
                ('X', models.TextField()),
                ('Y', models.TextField()),
                ('Z', models.TextField()),
                ('AA', models.TextField()),
                ('AB', models.TextField()),
                ('AC', models.TextField()),
                ('AD', models.TextField()),
                ('AE', models.TextField()),
                ('AF', models.TextField()),
                ('AG', models.TextField()),
                ('AH', models.TextField()),
                ('AI', models.TextField()),
                ('AJ', models.TextField()),
                ('AK', models.TextField()),
                ('AL', models.TextField()),
                ('AM', models.TextField()),
                ('AN', models.TextField()),
                ('AO', models.TextField()),
                ('AP', models.TextField()),
                ('AQ', models.TextField()),
                ('AR', models.TextField()),
                ('AS', models.TextField()),
                ('AT', models.TextField()),
                ('AU', models.TextField()),
                ('AV', models.TextField()),
                ('AW', models.TextField()),
                ('AX', models.TextField()),
                ('AY', models.TextField()),
            ],
        ),
    ]
