# Generated by Django 4.0.3 on 2022-03-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_importkey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importkey',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
